# Generated by Django 2.2.7 on 2019-12-12 02:57

from django.db import migrations, models
import django.db.models.deletion
import homeworkManage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManage', '0001_initial'),
        ('courseManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='作业id')),
                ('content', models.ImageField(null=True, upload_to=homeworkManage.models.homework_file, verbose_name='作业内容')),
                ('uploadtime', models.DateTimeField(verbose_name='上传时间')),
                ('score', models.FloatField(null=True, verbose_name='分数')),
                ('advice', models.CharField(max_length=2000, null=True, verbose_name='评语')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseManage.Course', verbose_name='课程')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManage.Students', verbose_name='学生')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManage.Teacher', verbose_name='评分老师')),
            ],
        ),
    ]
