# Generated by Django 2.2.7 on 2019-12-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生ID')),
                ('name', models.CharField(max_length=1000, verbose_name='学生姓名')),
                ('studentId', models.CharField(max_length=1000, verbose_name='学号')),
                ('phonenumber', models.CharField(max_length=1000, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=1000, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='教师ID')),
                ('name', models.CharField(max_length=1000, verbose_name='教师姓名')),
                ('teacherId', models.CharField(max_length=1000, verbose_name='教职工号')),
                ('phonenumber', models.CharField(max_length=1000, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=1000, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('loginTime', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('browser', models.CharField(max_length=1000, null=True, verbose_name='所用浏览器')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManage.Students', verbose_name='用户')),
            ],
        ),
    ]
