# Generated by Django 2.2.7 on 2019-12-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('name', models.CharField(max_length=1000, verbose_name='课程名称')),
                ('introduction', models.CharField(max_length=1000, null=True, verbose_name='课程简介')),
            ],
        ),
    ]
